nodeLinker: node-modules
initFields:
  type: module
  module: index.ts
  main: index.ts
  scripts:
    build: 'yarn run clean && yarn node "$(yarn bin esbuild)" --color=true --bundle --platform=node --sourcemap=inline --format=esm --main-fields=module,main --target=es2022 --out-extension:.js=.mjs'
    clean: 'rm -rf ./dist'
    lint: 'yarn biome lint --colors force --error-on-warnings .'
    script: 'yarn run build index=. --outdir=./dist && yarn node --experimental-vm-modules ./dist/index.mjs'
    test: 'yarn node --experimental-vm-modules --experimental-require-module "$(yarn bin jest)" --color'
  devDependencies:
    '@advent-of-code-2024/utils': 'workspace:*'
    '@biomejs/biome': '*'
    esbuild: '*'
    jest: '*'
  peerDependencies:
    '@babel/core': '*'
    '@babel/preset-env': '*'
    '@babel/preset-typescript': '*'
    '@biomejs/biome': '*'
    '@jest/globals': '^29.7.0'
    esbuild: '^0.24.0'
    jest: '^29.7.0'
changesetBaseRefs: origin/main
