nodeLinker: node-modules
initFields:
  type: module
  module: index.ts
  main: index.ts
  devDependencies:
    '@babel/preset-env': '^7.26.0'
    '@babel/preset-typescript': '^7.26.0'
    '@biomejs/biome': '^1.9.4'
    '@jest/globals': '^29.7.0'
    'esbuild': '^0.24.0'
    jest: '^29.7.0'
  scripts:
    build: 'yarn run clean && yarn node "$(yarn bin esbuild)" --color=true --bundle --platform=node --packages=external --sourcemap=inline --format=esm --main-fields=module,main --target=es2022 --out-extension:.js=.mjs'
    clean: 'rm -rf ./dist'
    lint: 'yarn biome lint --colors force --error-on-warnings .'
    run: 'yarn run build index=. --outdir=./dist && yarn node --experimental-vm-modules ./dist/index.mjs'
    test: 'yarn node --experimental-vm-modules --experimental-require-module "$(yarn bin jest)" --color'
changesetBaseRefs: origin/main

